apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitops-webapp
  labels:
    app: gitops-webapp
  annotations: 
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: webapp.dev.k8s.local
    http:
      paths:
      - backend:
          serviceName: gitops-webapp-svc
          servicePort: http

